// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5NSmQ0pN8Nf7k3GwBXxu73DePPJ4w9Do',
    appId: '1:535813158229:web:37f634c8a570beb374abdc',
    messagingSenderId: '535813158229',
    projectId: 'newshantika-7526d',
    authDomain: 'newshantika-7526d.firebaseapp.com',
    storageBucket: 'newshantika-7526d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Q-N3nVTYsNPG65EgDct9wmZjN5wAcFk',
    appId: '1:535813158229:android:d96829fd0e6184b674abdc',
    messagingSenderId: '535813158229',
    projectId: 'newshantika-7526d',
    storageBucket: 'newshantika-7526d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ2iDjXoyAYb9ArOnuod2JovglB8tUQUM',
    appId: '1:535813158229:ios:df4836bb1ca3008274abdc',
    messagingSenderId: '535813158229',
    projectId: 'newshantika-7526d',
    storageBucket: 'newshantika-7526d.appspot.com',
    iosClientId: '535813158229-pmefhjgibbug18o9enaki941728a3kd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shantikaBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ2iDjXoyAYb9ArOnuod2JovglB8tUQUM',
    appId: '1:535813158229:ios:df4836bb1ca3008274abdc',
    messagingSenderId: '535813158229',
    projectId: 'newshantika-7526d',
    storageBucket: 'newshantika-7526d.appspot.com',
    iosClientId: '535813158229-pmefhjgibbug18o9enaki941728a3kd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shantikaBus',
  );
}
